name: dlaf-env
store: /user-environment
spack:
    repo: https://github.com/spack/spack.git
    commit: develop-2024-10-06
mirror:
    enable: false
modules: false
description: "DLA-Future for 202410 status update"
