name: dlaf-env
store: /user-environment
spack:
    repo: file:///capstor/scratch/cscs/aurianer/install/spack_dlaf_new_stdexec
    commit: 883263340f079daff2d45168b4f9200548ef5cae
mirror:
    enable: true
modules: false
description: "DLA-Future for 202410 status update"
